#!/bin/sh

echo "Hello! I am pre-commit hook"

if [ "$(git config --get devsecops.protect.enabled)" != "true" ]; then
    echo "Skipping protect by gitleaks..."
    exit 0
fi
echo "Enforcing DevSecOps protect..."

set -e
SCRIPT_DIR=$1
LOCAL_SHIFTLEFT=$1/kbot-devsecops/shiftleft
SOURCE_PATH=$(git rev-parse --show-toplevel)
echo "$SOURCE_PATH"

if ! "$LOCAL_SHIFTLEFT/gitleaks" version
then
    . "$LOCAL_SHIFTLEFT/gitleaks-install.sh" "$LOCAL_SHIFTLEFT"
fi

"$LOCAL_SHIFTLEFT/gitleaks" protect --staged --source "$SOURCE_PATH" -v

echo "Bye, thanks! DevSecOps pre-commit protection passed."
